src/Entity/Thread.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ThreadRepository")
 */
class Thread
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Message")
     * @ORM\JoinColumn(nullable=true)
     */
    private $last_message;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="thread", orphanRemoval=true)
     */
    private $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getLastMessage(): ?string
    {
        return $this->last_message;
    }

    public function setLastMessage(?string $last_message): self
    {
        $this->last_message = $last_message;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setThread($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getThread() === $this) {
                $message->setThread(null);
            }
        }

        return $this;
    }
}

src/Form/ThreadType.php
<?php

namespace App\Form;

use App\Entity\Thread;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ThreadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Thread::class,
        ]);
    }
}

src/Controller/ThreadController.php
<?php

namespace App\Controller;

use App\Entity\Thread;
use App\Entity\User;
use App\Form\ThreadType;
use App\Repository\ThreadRepository;
use DateTime;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ThreadController extends AbstractController
{
    /**
     * @Route("/", name="threads")
     * @param ThreadRepository $threadRepository
     * @return Response
     */
    public function index(ThreadRepository $threadRepository)
    {
        $threads = $threadRepository->findAll();
        return $this->render('thread/index.html.twig', [
            'threads' => $threads
        ]);
    }

    /**
     * @Route("/new-thread", name="create-thread")
     * @param Request $request
     * @return Response
     * @throws Exception
     */
    public function createThread(Request $request): Response
    {
        $thread = new Thread();
        $form = $this->createForm(ThreadType::class, $thread);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // If User authentication was implemented: $thread->setAuthor($this->getUser());
            $user = $this->getDoctrine()->getRepository(User::class)->find(1);
            $thread->setAuthor($user);

            $thread->setDate(new DateTime());

            $em = $this->getDoctrine()->getManager();
            $em->persist($thread);
            $em->flush();

            return $this->redirectToRoute('threads');
        }

        return $this->render('thread/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/thread/{id}", name="view-thread")
     * @ParamConverter("thread", class="App\Entity\Thread")
     * @param Thread $thread
     * @return Response
     */
    public function viewThread(Thread $thread): Response
    {
        $messages = $thread->getMessages();

        return $this->render('thread/view.html.twig', [
            'messages' => $messages,
            'thread' => $thread
        ]);
    }
}

templates/thread/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create!{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">
        {{ form(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/thread/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Threads!{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">
        <table>
            {% for thread in threads %}
                <tr>
                    <td><a href="{{ path('view-thread', {'id': thread.id}) }}">{{ thread.name }}</a></td>
                    {% if thread.lastMessage.date is defined %}
                        <td>{{ thread.lastMessage.date|date('Y-m-d') }}</td>{% else %}<td>{{ thread.date|date('Y-m-d m:s') }}</td>{% endif %}
                    <td>{{ thread.author.username }}</td>
                </tr>
            {% endfor %}
        </table>
        <br/>
        <a href="{{ path('create-thread') }}">Nové téma</a>

    </div>
{% endblock %}

templates/thread/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ thread.name }}{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">
        {% for message in messages %}
            <div class="message">
                <div class="author">{{ message.author.username }}</div>
                <div class="date">{{ message.date|date('Y-m-d h:s') }}</div>
                <div class="content">{{ message.content }}</div>
            </div>
        {% endfor %}
        <a href="{{ path('create-message', {'id': thread.id}) }}">Nová zpráva</a>
    </div>
{% endblock %}